// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import "dotenv/config";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

config({
  path: resolve(process.cwd(), '../../.env'),
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["CORE_DATABASE_URL"],
  },
});
