apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: reports
          image: jagoan-pos/reports:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 4004
          envFrom:
            - configMapRef:
                name: service-config
            - secretRef:
                name: reports-env
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 10
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: reports
spec:
  selector:
    app: reports
  ports:
    - name: tcp
      port: 4004
      targetPort: tcp
  type: ClusterIP
